version: "2"

services:
  django_api:
    build:
      context: .
      dockerfile: ./docker/django_api/Dockerfile
    environment:
      # us production-like settings without SSL locally
      # override file uses development settings
      - DJANGO_SETTINGS_MODULE=meron_api.settings.insecure
      - DJANGO_SECRET_KEY=voruuth2eexeZ6haiNgajae9ohme3aixb6\xe8\x0c\x90\x1f
      - DJANGO_ALLOWED_HOSTS=localhost,127.0.0.1
      - UID=${UID:-1000}
      - DJANGO_DEBUG=False

  nginx:
    build:
      context: docker/nginx
    depends_on:
      - django_api
    environment:
      - DOMAIN=localhost
      - NGINX_WORKER_PROCESSES=1
      # For fluentd logging use the following line instead:
      #- NGINX_ACCESS_LOGFORMAT=fluentd_json
      - NGINX_ACCESS_LOGFORMAT=combined
      - NGINX_PROXY_READ_TIMEOUT=300
    ports:
      - 80:80
