version: "2"

services:
  django_api:
    volumes:
      # project directory is mounted (but read-only), so changes to the source code
      # are picked up by development server
      - ${PWD}/meron_api:/app/meron_api:ro
      - ${PWD}/docker:/app/docker:ro
    environment:
      - DJANGO_SETTINGS_MODULE=meron_api.settings.development
      # this instructs settings to add the Docker IP to INTERNAL_IPS, for django-debug-toolbar
      - USE_DOCKER=yes
      - DJANGO_DEBUG=True
    ports:
      - "5000:5000"
    # in development, we will run the Django dev server instead of gunicorn
    command: python manage.py runserver 0.0.0.0:5000
